version: "3.9"

services:
  db:
    image: postgres:15
    container_name: smartparis-db
    restart: always
    environment:
      POSTGRES_USER: smartparis
      POSTGRES_PASSWORD: smartparis
      POSTGRES_DB: smartparis_db
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  backend:
    build: ./backend
    container_name: smartparis-backend
    restart: always
    depends_on:
      - db
    environment:
      DATABASE_HOST: db
      DATABASE_PORT: 5432
      DATABASE_USER: smartparis
      DATABASE_PASSWORD: smartparis
      DATABASE_NAME: smartparis_db
      JWT_SECRET: supersecret
      PORT: 5000
    ports:
      - "5000:5000"
    volumes:
      - ./backend:/app
      - /app/node_modules

  frontend:
    build: ./frontend
    container_name: smartparis-frontend
    restart: always
    depends_on:
      - backend
    environment:
      VITE_API_URL: http://localhost:5000/api
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules

volumes:
  db_data:
